#Configure Port Number
server:  port: 8400
 

spring:
  datasource:    url: jdbc:oracle:thin:@localhost:1521/XE
    username: rentcollect
    password: rentcollect
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.Oracle10gDialect